# Fitbit Stuff

FITBIT_CLIENT_KEY = ''
FITBIT_CLIENT_SECRET = ''

FITBIT_USER_KEY = ''
FITBIT_USER_SECRET = ''

FITBIT_REQUEST_TOKEN_URL = ''
FITBIT_ACCESS_TOKEN_URL = ''
FITBIT_AUTHORIZATION_URL = ''

# Map My Fitness API

MMF_CLIENT_KEY = ''
MMF_SECRET_KEY = ''
